### ISSUE TITLE
You could try being more subtle about using other people's code without even asking and then crediting yourself for the work

### ISSUE THREAD

**Issue by hoxiwoopboop** [RedFlamer/Reworked-Enemy-AI#7]
https://cdn.discordapp.com/attachments/442451692731236352/876255673472671744/Screenshot_20210814-190700_Discord.jpg

**Comment by hoxiwoopboop** [comment]
Vanilla:
![_set_new_pos (vanilla)](https://user-images.githubusercontent.com/44041474/129463816-c1d10633-fdac-4235-94a4-845e53711d91.png)

Crackdown:
![_set_new_pos (Crackdown)](https://user-images.githubusercontent.com/44041474/129463817-b5070d4f-3f05-42c7-8183-4b4274df521b.png)

The code in this repo when decompiled (or well, attempted to)
![_set_new_pos (attempted decompile from Reworked-Enemy-AI)](https://user-images.githubusercontent.com/44041474/129463818-15d4fea8-baa6-4afc-ae1c-8cd8a8fff646.png)

You didn't even bother correcting my mistakes with raw Vector3 math which I didn't know at the time, where I should have used mvector3 mutable math for better performance. Like in this case here where vanilla does it properly.

**Comment by RedFlamer** [comment]
So you cherrypicked an example where i made the same mistake as you when implementations are naturally going to be similar and then claim i stole your work?

Frankly i don't care to argue if it's going to be a waste of time, bother someone who cares.

**Comment by connieprice** [comment]
Acting so defensive about this, plus with bytecode compiled Lua files, not suspicious at all. This, along with your instant aggressiveness, isn't a great look.

Why are you trying to hide code behind compilation? This is one of your only repositories that does it, which is even stranger.
